services:
    misha_fpm:
        container_name: misha_fpm
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                WORKING_DIR: ${WORKING_DIR}
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 4.28.1
        ports:
            - "${PHP_PORT}:9000"
        environment:
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        volumes:
            - ./:${WORKING_DIR}
            - ./var/log/php-fpm:/var/log/php-fpm
        working_dir: ${WORKING_DIR}

    misha_nginx:
        container_name: misha_nginx
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:${WORKING_DIR}
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./var/log/nginx:/var/log/nginx
        depends_on:
            - misha_fpm
